name: Continuous Integration

run-name: Run ${{ github.workflow }} on ${{ github.ref_name }} - ${{ github.action }} by ${{ github.actor }}

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - apps/api/**
            - apps/web/**
            - packages/domain/**
            - .github/workflows/ci.yml
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
        paths:
            - apps/api/**
            - apps/web/**
            - packages/domain/**
            - .github/workflows/ci.yml

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    detect-changes:
        runs-on: ubuntu-24.04
        timeout-minutes: 2
        outputs:
            api: "${{ steps.detect-changes.outputs.api }}"
            web: "${{ steps.detect-changes.outputs.web }}"
            domain: "${{ steps.detect-changes.outputs.domain }}"
            any: "${{ steps.set-changes-output.outputs.any }}"
        steps:
            - name: Checkout
              id: git-checkout
              timeout-minutes: 1
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            - name: Detect Changes
              id: detect-changes
              uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
              with:
                filters: |
                  api:
                    - 'apps/api/**'
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'
                  web:
                    - 'apps/web/**'
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'
                  domain:
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'

            - name: Set Any Changes Output
              id: set-changes-output
              timeout-minutes: 1
              run: |
                if [[ "${{ steps.detect-changes.outputs.api }}" == "true" || "${{ steps.detect-changes.outputs.web }}" == "true" || "${{ steps.detect-changes.outputs.domain }}" == "true" ]]; then
                    echo "any=true" >> "$GITHUB_OUTPUT"
                else
                    echo "any=false" >> "$GITHUB_OUTPUT"
                fi

    resolve-configs:
        runs-on: ubuntu-24.04
        timeout-minutes: 1
        environment: "testing"
        outputs:
            node-version: ${{ steps.resolve-conf.outputs.node-version }}
            coverage-threshold: ${{ steps.resolve-conf.outputs.coverage-threshold }}
        steps:
            - name: Resolve configurations for environment.
              id: resolve-conf
              timeout-minutes: 1
              run: |
                echo "node-version=${{ vars.NODE_VERSION }}" >> "$GITHUB_OUTPUT"
                echo "coverage-threshold=${{ vars.COVERAGE_THRESHOLD }}" >> "$GITHUB_OUTPUT"

    setup-pulsecart:
        needs: [detect-changes, resolve-configs]
        if: needs.detect-changes.outputs.any == 'true'
        runs-on: ubuntu-24.04
        timeout-minutes: 5
        steps:
            - name: Checkout
              id: git-checkout
              timeout-minutes: 1
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            - name: Setup Node and Dependencies
              id: setup-node-deps
              timeout-minutes: 4
              uses: ./.github/actions/setup-pulsecart
              with:
                node-version: ${{ needs.resolve-configs.outputs.node-version }}

    api-linters:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.api == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm lint
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/api
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'false'

    api-unit-tests:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.api == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm test:unit
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/api
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'true'

    api-integration-tests:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.api == 'true'
        uses: ./.github/workflows/reusable-integration-node-checks.yml
        with:
            command: pnpm test:integration
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/api

    web-linters:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.web == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm lint
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/web
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'false'

    web-unit-tests:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.web == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm test:unit
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/web
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'true'

    web-e2e-tests:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.web == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm test:e2e
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: apps/web
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'false'

    domain-linters:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.domain == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm lint
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: ""
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'false'

    domain-unit-tests:
        needs: [detect-changes, resolve-configs, setup-pulsecart]
        if: needs.detect-changes.outputs.domain == 'true'
        uses: ./.github/workflows/reusable-node-checks.yml
        with:
            command: pnpm test:unit
            node-version: ${{ needs.resolve-configs.outputs.node-version }}
            workspace: ""
            coverage-threshold: ${{ needs.resolve-configs.outputs.coverage-threshold }}
            upload-artifacts: 'false'