name: Continuous Integration
run-name: Run ${{ github.workflow }} on ${{ github.ref_name }} - ${{ github.action }} by ${{ github.actor }}
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - apps/api/**
            - apps/web/**
            - packages/domain/**
            - .github/workflows/ci.yml
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
        paths:
            - apps/api/**
            - apps/web/**
            - packages/domain/**
            - .github/workflows/ci.yml
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
env:
    WORKING_DIRECTORY: ${{ github.workspace }}
jobs:
    detect-changes:
        runs-on: ubuntu-24.04
        timeout-minutes: 2
        # permissions: 
        outputs:
            api: "${{ steps.detect-changes.outputs.api }}"
            web: "${{ steps.detect-changes.outputs.web }}"
            domain: "${{ steps.detect-changes.outputs.domain }}"
            any: "${{ steps.set-changes-output.outputs.any }}"
        steps:
            - uses: ./.github/actions/checkout
              with:
                working-directory: "${{ env.WORKING_DIRECTORY }}"

            - name: Detect Changes
              id: detect-changes
              uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
              with:
                working-directory: "${{ env.WORKING_DIRECTORY }}"
                filters: |
                  api:
                    - 'apps/api/**'
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'
                  web:
                    - 'apps/web/**'
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'
                  domain:
                    - 'packages/domain/**'
                    - 'package.json'
                    - 'pnpm-lock.yaml'
                    - '.github/workflows/ci.yml'

            - name: Set Any Changes Output
              id: set-changes-output
              timeout-minutes: 1
              shell: bash
              run: |
                if [[ "${{ steps.detect-changes.outputs.api }}" == "true" || "${{ steps.detect-changes.outputs.web }}" == "true" || "${{ steps.detect-changes.outputs.domain }}" == "true" ]]; then
                    echo "any=true" >> "$GITHUB_OUTPUT"
                else
                    echo "any=false" >> "$GITHUB_OUTPUT"
                fi
    
    lint:
        needs: detect-changes
        if: needs.detect-changes.outputs.any == 'true'
        runs-on: ubuntu-24.04
        timeout-minutes: 5
        steps:
            - uses: ./.github/actions/checkout
              with:
                working-directory: "${{ env.WORKING_DIRECTORY }}"
                
            - uses: ./.github/actions/setup-node
              with:
                working-directory: "${{ env.WORKING_DIRECTORY }}"

            - name: API | Run Linters
              id: api-run-linters
              if: needs.detect-changes.outputs.api == 'true'
              shell: bash
              working-directory: "${{ env.WORKING_DIRECTORY }}/apps/api"
              run: pnpm lint

            - name: WEB | Run Linters
              id: web-run-linters
              if: needs.detect-changes.outputs.web == 'true'
              shell: bash
              working-directory: "${{ env.WORKING_DIRECTORY }}/apps/web"
              run: pnpm lint
              
            - name: DOMAIN | Run Linters
              id: domain-run-linters
              if: needs.detect-changes.outputs.domain == 'true'
              shell: bash
              working-directory: "${{ env.WORKING_DIRECTORY }}/packages/domain"
              run: pnpm lint